baseURL = "https://tathagat10.com"
title = "tathagat10"
[pagination]
  pagerSize = 5
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "tathagat's blog"
  description = "a software engineer writing stuff, i like cars and tech"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Tathagata Talukdar"
  # author = ["Me", "You"] # multiple authors
  images = ["/images/profile.jpg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    disableHLJS = true
    disableFingerprinting = true
    favicon = "/icons/tt32.png"
    favicon16x16 = "/icons/tt16.png"
    favicon32x32 = "/icons/tt32.png"
    apple_touch_icon = "/icons/tt512.png"
    safari_pinned_tab = "/icons/tt1024.png"

  [params.label]
    text = "Home"
    icon = "/icons/tt512.png"
    iconHeight = 35

  [params.profileMode]
    enabled = true
    title = "Tathagata Talukdar"
    subtitle = "a software engineer writing stuff, i like cars and tech"
    imageUrl = "/images/profile.jpg"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"
    
    [[params.profileMode.buttons]]
      name = "blogs"
      url = "/blogs"

  [params.homeInfoParams]
    Title = "Tathagata Talukdar"
    Content = "a software engineer writing stuff"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/tathagata-talukdar/"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/tathagat11"
  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/audishun"

  [params.analytics]
    [params.analytics.google]
      SiteVerificationTag = "XYZabc"
    [params.analytics.bing]
      SiteVerificationTag = "XYZabc"
    [params.analytics.yandex]
      SiteVerificationTag = "XYZabc"

  [params.cover]
    hidden = false
    hiddenInList = true
    hiddenInSingle = false

  [params.editPost]
    URL = "https://github.com/tathagat11/blog/content"
    Text = "Suggest Changes"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    limit = 10
    keys = ["title", "permalink", "summary", "content"]

# [[menu.main]]
#  identifier = "categories"
#  name = "categories"
#  url = "/categories/"
#  weight = 10
[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 20
# [[menu.main]]
#  identifier = "example"
#  name = "example.org"
#  url = "https://example.org"
#  weight = 30

pygmentsUseClasses = true

[markup]
  [markup.highlight]
    noClasses = false
    # anchorLineNos = true
    # codeFences = true
    # guessSyntax = true
    # lineNos = true
    # style = monokai